services:
  floradecora:
    build:
      context: ./floradecora
      dockerfile: Dockerfile
    container_name: floradecora
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
