export type FieldDef =
  | { kind: "text"; path: string; label: string }
  | { kind: "textarea"; path: string; label: string; rows?: number }
  | { kind: "image"; path: string; label: string }
  | { kind: "number"; path: string; label: string }
  | { kind: "list"; path: string; label: string; itemString?: boolean; itemFields?: FieldDef[]; addLabel?: string };

export type ContentSection = {
  key: string;
  title: string;
  description?: string;
  fields: FieldDef[];
};

const NAV_ITEM: FieldDef[] = [
  { kind: "text", path: "href", label: "Link" },
  { kind: "text", path: "label", label: "Label (EN)" },
  { kind: "text", path: "labelAr", label: "Label (AR)" },
];

export const CONTENT_SECTIONS: ContentSection[] = [
  {
    key: "site_header",
    title: "Header / Navigation",
    description: "Main menu links and the header call-to-action button.",
    fields: [
      { kind: "list", path: "nav", label: "Nav links", itemFields: NAV_ITEM, addLabel: "Add link" },
      { kind: "text", path: "cta.label", label: "CTA button (EN)" },
      { kind: "text", path: "cta.labelAr", label: "CTA button (AR)" },
    ],
  },
  {
    key: "site_footer",
    title: "Footer",
    description: "Footer blurb, link columns, social icons and bottom bar.",
    fields: [
      { kind: "textarea", path: "blurb", label: "Blurb", rows: 4 },
      { kind: "text", path: "exploreHeading", label: '"Explore" heading' },
      { kind: "list", path: "exploreLinks", label: "Explore links", itemFields: [{ kind: "text", path: "href", label: "Link" }, { kind: "text", path: "label", label: "Label" }], addLabel: "Add link" },
      { kind: "text", path: "servicesHeading", label: '"Services" heading' },
      { kind: "list", path: "servicesLinks", label: "Services links", itemFields: [{ kind: "text", path: "href", label: "Link" }, { kind: "text", path: "label", label: "Label" }], addLabel: "Add link" },
      { kind: "list", path: "social", label: "Social icons", itemFields: [{ kind: "text", path: "icon", label: "Icon (instagram / linkedin / youtube / link)" }, { kind: "text", path: "label", label: "Name" }, { kind: "text", path: "href", label: "URL" }], addLabel: "Add social link" },
      { kind: "text", path: "copyright", label: 'Copyright ({year} = current year)' },
      { kind: "text", path: "availability", label: "Availability note" },
    ],
  },
  {
    key: "site_contact",
    title: "Contact Info",
    description: "Shared phone, email, address and hours — used by the footer, contact page, JSON-LD and CTA buttons.",
    fields: [
      { kind: "text", path: "addressShort", label: "Address (short, footer)" },
      { kind: "list", path: "addressLines", label: "Address (full, contact page)", itemString: true, addLabel: "Add line" },
      { kind: "text", path: "phone", label: "Phone (display)" },
      { kind: "text", path: "phoneDial", label: "Phone (tel: link)" },
      { kind: "text", path: "email", label: "Email" },
      { kind: "text", path: "hours", label: "Hours" },
      { kind: "text", path: "hoursNote", label: "Hours note" },
      { kind: "text", path: "replyTime", label: "Reply time badge" },
      { kind: "text", path: "replyNote", label: "Reply note" },
    ],
  },
  {
    key: "site_whatsapp",
    title: "WhatsApp Widget",
    fields: [
      { kind: "text", path: "phone", label: "Phone (digits only)" },
      { kind: "text", path: "message", label: "Pre-filled message" },
    ],
  },
  {
    key: "site_seo",
    title: "SEO / Social Sharing",
    description: "Page title, meta description and social preview texts.",
    fields: [
      { kind: "text", path: "title", label: "Site title (homepage)" },
      { kind: "textarea", path: "description", label: "Meta description", rows: 4 },
      { kind: "list", path: "keywords", label: "Meta keywords", itemString: true, addLabel: "Add keyword" },
      { kind: "textarea", path: "ogDescription", label: "Facebook/OG description", rows: 3 },
      { kind: "text", path: "twitterTitle", label: "X/Twitter title" },
      { kind: "text", path: "twitterDescription", label: "X/Twitter description" },
      { kind: "text", path: "siteName", label: "Site name" },
    ],
  },
  {
    key: "site_jsonld",
    title: "Structured Data (Google)",
    description: "LocalBusiness JSON-LD. Phone/email/address come from Contact Info above.",
    fields: [
      { kind: "text", path: "name", label: "Business name" },
      { kind: "textarea", path: "description", label: "Description", rows: 3 },
      { kind: "image", path: "logo", label: "Logo URL" },
      { kind: "image", path: "image", label: "Image URL" },
      { kind: "text", path: "streetAddress", label: "Street address" },
      { kind: "text", path: "locality", label: "City" },
      { kind: "text", path: "region", label: "Region" },
      { kind: "text", path: "country", label: "Country code" },
      { kind: "text", path: "foundingDate", label: "Founded" },
      { kind: "text", path: "priceRange", label: "Price range" },
    ],
  },
  {
    key: "page_home",
    title: "Homepage",
    description: "Hero, stats, about, gallery, concepts, services, process and CTA sections.",
    fields: [
      { kind: "text", path: "hero.badge", label: "Hero badge" },
      { kind: "text", path: "hero.badgeChip", label: "Hero badge chip" },
      { kind: "text", path: "hero.titleLine1", label: "Title line 1" },
      { kind: "text", path: "hero.titleLine2", label: "Title line 2 (gradient)" },
      { kind: "text", path: "hero.titleLine3", label: "Title line 3" },
      { kind: "textarea", path: "hero.subtitle", label: "Hero subtitle", rows: 4 },
      { kind: "text", path: "hero.primaryCta", label: "Primary button" },
      { kind: "text", path: "hero.secondaryCta", label: "Secondary button" },
      { kind: "text", path: "hero.trusted", label: "Trusted note" },
      { kind: "text", path: "hero.rating", label: "Rating line" },
      { kind: "text", path: "hero.ratingBy", label: "Rating source" },
      { kind: "image", path: "hero.bgImage", label: "Hero background" },
      { kind: "image", path: "hero.circleImage", label: "Hero circle image" },
      { kind: "image", path: "hero.featureImage", label: "Featured card image" },
      { kind: "text", path: "hero.featureLabel", label: "Featured card label" },
      { kind: "text", path: "hero.featureTitle", label: "Featured card title" },
      { kind: "image", path: "hero.irrigationImage", label: "Side card image" },
      { kind: "text", path: "hero.irrigationTitle", label: "Side card title" },
      { kind: "text", path: "hero.irrigationNote", label: "Side card note" },
      { kind: "text", path: "hero.statValue", label: "Projects badge value" },
      { kind: "text", path: "hero.statNote", label: "Projects badge note" },
      { kind: "list", path: "hero.marquee", label: "Marquee keywords", itemString: true, addLabel: "Add keyword" },
      { kind: "list", path: "stats", label: "Stats row", addLabel: "Add stat", itemFields: [
        { kind: "number", path: "n", label: "Number" },
        { kind: "text", path: "suffix", label: "Suffix (e.g. +)" },
        { kind: "text", path: "label", label: "Label" },
        { kind: "text", path: "sub", label: "Sub-label" },
      ] },
      { kind: "text", path: "about.eyebrow", label: "About eyebrow" },
      { kind: "text", path: "about.title", label: "About title" },
      { kind: "list", path: "about.features", label: "About feature chips", addLabel: "Add chip", itemFields: [
        { kind: "text", path: "k", label: "Number" },
        { kind: "text", path: "v", label: "Text" },
      ] },
      { kind: "textarea", path: "about.p1", label: "About paragraph 1", rows: 4 },
      { kind: "textarea", path: "about.p2", label: "About paragraph 2", rows: 4 },
      { kind: "text", path: "about.cta", label: "About button" },
      { kind: "image", path: "about.image", label: "About image" },
      { kind: "text", path: "about.liveChip", label: "Live site chip" },
      { kind: "text", path: "about.teamValue", label: "Horticulturists value" },
      { kind: "text", path: "about.teamLabel", label: "Horticulturists label" },
      { kind: "text", path: "about.coverageLabel", label: "Coverage label" },
      { kind: "text", path: "about.coverageValue", label: "Coverage value" },
      { kind: "text", path: "gallery.eyebrow", label: "Gallery eyebrow" },
      { kind: "text", path: "gallery.title", label: "Gallery title" },
      { kind: "text", path: "gallery.cta", label: "Gallery button" },
      { kind: "textarea", path: "gallery.intro", label: "Gallery intro", rows: 3 },
      { kind: "list", path: "gallery.items", label: "Gallery projects", addLabel: "Add project", itemFields: [
        { kind: "image", path: "src", label: "Image" },
        { kind: "text", path: "title", label: "Title" },
        { kind: "text", path: "meta", label: "Meta line" },
      ] },
      { kind: "list", path: "gallery.thumbs", label: "Thumbnail strip", itemString: true, addLabel: "Add image URL" },
      { kind: "text", path: "concepts.eyebrow", label: "Concepts eyebrow" },
      { kind: "text", path: "concepts.title", label: "Concepts title" },
      { kind: "text", path: "concepts.badge", label: "Concepts badge" },
      { kind: "textarea", path: "concepts.intro", label: "Concepts intro", rows: 3 },
      { kind: "list", path: "concepts.items", label: "AI concept renders", addLabel: "Add concept", itemFields: [
        { kind: "image", path: "src", label: "Image" },
        { kind: "text", path: "label", label: "Label" },
      ] },
      { kind: "text", path: "services.eyebrow", label: "Services eyebrow" },
      { kind: "text", path: "services.title", label: "Services title" },
      { kind: "textarea", path: "services.intro", label: "Services intro", rows: 3 },
      { kind: "text", path: "services.cta", label: "Services button" },
      { kind: "text", path: "services.explore", label: "Service card hover label" },
      { kind: "text", path: "process.eyebrow", label: "Process eyebrow" },
      { kind: "text", path: "process.title", label: "Process title" },
      { kind: "list", path: "process.steps", label: "Process steps", addLabel: "Add step", itemFields: [
        { kind: "text", path: "phase", label: "Phase" },
        { kind: "text", path: "title", label: "Title" },
        { kind: "list", path: "points", label: "Points", itemString: true, addLabel: "Add point" },
        { kind: "text", path: "color", label: "Dot color class (bg-ochre / bg-sage / bg-forest)" },
      ] },
      { kind: "text", path: "cta.chip", label: "CTA chip" },
      { kind: "text", path: "cta.title", label: "CTA title" },
      { kind: "textarea", path: "cta.sub", label: "CTA subtitle", rows: 3 },
      { kind: "text", path: "cta.primary", label: "CTA primary button" },
      { kind: "text", path: "cta.secondary", label: "CTA phone button" },
      { kind: "list", path: "cta.tags", label: "CTA tags", itemString: true, addLabel: "Add tag" },
    ],
  },
  {
    key: "page_about",
    title: "About Page",
    fields: [
      { kind: "text", path: "meta.title", label: "SEO title" },
      { kind: "textarea", path: "meta.description", label: "SEO description", rows: 3 },
      { kind: "text", path: "hero.badge", label: "Hero badge" },
      { kind: "text", path: "hero.titleLead", label: "Hero title (before highlight)" },
      { kind: "text", path: "hero.titleHighlight", label: "Hero title (highlight word)" },
      { kind: "text", path: "hero.titleRest", label: "Hero title (after highlight)" },
      { kind: "image", path: "hero.image", label: "Hero image" },
      { kind: "textarea", path: "intro.lead", label: "Intro lead paragraph", rows: 3 },
      { kind: "textarea", path: "intro.p2", label: "Intro paragraph 2", rows: 3 },
      { kind: "image", path: "intro.image", label: "Intro image" },
      { kind: "textarea", path: "intro.p3", label: "Intro paragraph 3", rows: 3 },
      { kind: "text", path: "intro.quote", label: "Intro quote" },
      { kind: "text", path: "mission.eyebrow", label: "Mission eyebrow" },
      { kind: "text", path: "mission.title", label: "Mission title" },
      { kind: "textarea", path: "mission.body", label: "Mission body", rows: 3 },
      { kind: "list", path: "mission.values", label: "Values", addLabel: "Add value", itemFields: [
        { kind: "text", path: "icon", label: "Icon" },
        { kind: "text", path: "title", label: "Title" },
        { kind: "textarea", path: "body", label: "Body", rows: 3 },
      ] },
      { kind: "text", path: "principles.eyebrow", label: "Principles eyebrow" },
      { kind: "text", path: "principles.title", label: "Principles title" },
      { kind: "textarea", path: "principles.intro", label: "Principles intro", rows: 3 },
      { kind: "list", path: "principles.items", label: "Principles", addLabel: "Add principle", itemFields: [
        { kind: "text", path: "title", label: "Title" },
        { kind: "textarea", path: "body", label: "Body", rows: 3 },
      ] },
      { kind: "text", path: "timeline.eyebrow", label: "Timeline eyebrow" },
      { kind: "text", path: "timeline.title", label: "Timeline title" },
      { kind: "list", path: "timeline.events", label: "Timeline events", addLabel: "Add event", itemFields: [
        { kind: "text", path: "year", label: "Year" },
        { kind: "text", path: "title", label: "Title" },
        { kind: "text", path: "desc", label: "Description" },
      ] },
      { kind: "text", path: "testimonials.eyebrow", label: "Testimonials eyebrow" },
      { kind: "text", path: "testimonials.title", label: "Testimonials title" },
      { kind: "list", path: "testimonials.chips", label: "Trust chips", itemString: true, addLabel: "Add chip" },
      { kind: "list", path: "testimonials.reviews", label: "Reviews", addLabel: "Add review", itemFields: [
        { kind: "text", path: "name", label: "Name" },
        { kind: "text", path: "role", label: "Role" },
        { kind: "textarea", path: "text", label: "Quote", rows: 4 },
        { kind: "number", path: "rating", label: "Stars (1-5)" },
      ] },
      { kind: "text", path: "faq.eyebrow", label: "FAQ eyebrow" },
      { kind: "text", path: "faq.title", label: "FAQ title" },
      { kind: "list", path: "faq.items", label: "FAQ items", addLabel: "Add question", itemFields: [
        { kind: "text", path: "q", label: "Question" },
        { kind: "textarea", path: "a", label: "Answer", rows: 4 },
      ] },
    ],
  },
  {
    key: "page_contact",
    title: "Contact Page",
    fields: [
      { kind: "text", path: "meta.title", label: "SEO title" },
      { kind: "textarea", path: "meta.description", label: "SEO description", rows: 3 },
      { kind: "text", path: "hero.badge", label: "Hero badge" },
      { kind: "text", path: "hero.title", label: "Hero title" },
      { kind: "image", path: "hero.image", label: "Hero image" },
      { kind: "text", path: "card.officeLabel", label: '"Office" label' },
      { kind: "text", path: "card.phoneLabel", label: '"Phone" label' },
      { kind: "text", path: "card.emailLabel", label: '"Email" label' },
      { kind: "text", path: "card.hoursLabel", label: '"Hours" label' },
      { kind: "image", path: "card.mapImage", label: "Map card image" },
      { kind: "text", path: "card.mapChip", label: "Map chip" },
      { kind: "text", path: "card.formTitle", label: "Form card title" },
      { kind: "text", path: "form.name", label: 'Field: "Full name"' },
      { kind: "text", path: "form.email", label: 'Field: "Email address"' },
      { kind: "text", path: "form.phone", label: 'Field: "Phone"' },
      { kind: "text", path: "form.projectType", label: 'Field: "Project type"' },
      { kind: "text", path: "form.projectTypePlaceholder", label: "Project type placeholder" },
      { kind: "text", path: "form.messageLabel", label: 'Field: "Message"' },
      { kind: "text", path: "form.messagePlaceholder", label: "Message placeholder" },
      { kind: "text", path: "form.submit", label: "Submit button" },
      { kind: "text", path: "form.sending", label: "Sending state" },
      { kind: "textarea", path: "form.success", label: "Success message", rows: 3 },
      { kind: "textarea", path: "form.errorFallback", label: "Error fallback message", rows: 3 },
      { kind: "text", path: "form.validationName", label: "Validation: name" },
      { kind: "text", path: "form.validationEmail", label: "Validation: email" },
      { kind: "text", path: "form.validationMessage", label: "Validation: message length" },
    ],
  },
  {
    key: "page_services",
    title: "Services Page",
    fields: [
      { kind: "text", path: "meta.title", label: "SEO title" },
      { kind: "textarea", path: "meta.description", label: "SEO description", rows: 3 },
      { kind: "text", path: "hero.badge", label: "Hero badge" },
      { kind: "text", path: "hero.title", label: "Hero title" },
      { kind: "textarea", path: "hero.subtitle", label: "Hero subtitle", rows: 3 },
      { kind: "text", path: "cta.title", label: "Bottom CTA title" },
      { kind: "text", path: "cta.subtitle", label: "Bottom CTA subtitle" },
      { kind: "text", path: "cta.button", label: "Bottom CTA button" },
    ],
  },
  {
    key: "page_projects",
    title: "Projects Page",
    fields: [
      { kind: "text", path: "meta.title", label: "SEO title" },
      { kind: "textarea", path: "meta.description", label: "SEO description", rows: 3 },
      { kind: "text", path: "hero.badge", label: "Hero badge ({count} = project count)" },
      { kind: "text", path: "hero.title", label: "Hero title" },
      { kind: "textarea", path: "hero.subtitle", label: "Hero subtitle", rows: 3 },
      { kind: "image", path: "hero.image", label: "Hero image" },
      { kind: "list", path: "stats", label: "Stats row (first stat counts case studies)", addLabel: "Add stat", itemFields: [
        { kind: "number", path: "n", label: "Number" },
        { kind: "text", path: "suffix", label: "Suffix" },
        { kind: "text", path: "label", label: "Label" },
      ] },
      { kind: "text", path: "section.eyebrow", label: "Section eyebrow" },
      { kind: "text", path: "section.title", label: "Section title" },
      { kind: "text", path: "section.helper", label: "Helper text" },
      { kind: "text", path: "section.searchPlaceholder", label: "Search placeholder" },
    ],
  },
  {
    key: "page_blog",
    title: "Blog Page",
    fields: [
      { kind: "text", path: "meta.title", label: "SEO title" },
      { kind: "textarea", path: "meta.description", label: "SEO description", rows: 3 },
      { kind: "text", path: "hero.badge", label: "Hero badge" },
      { kind: "text", path: "hero.title", label: "Hero title" },
      { kind: "text", path: "section.eyebrow", label: "Section eyebrow" },
      { kind: "text", path: "section.title", label: "Section title" },
      { kind: "text", path: "section.readLabel", label: '"Read" link' },
      { kind: "text", path: "newsletter.badge", label: "Newsletter badge" },
      { kind: "text", path: "newsletter.title", label: "Newsletter title" },
      { kind: "textarea", path: "newsletter.subtitle", label: "Newsletter subtitle", rows: 3 },
      { kind: "text", path: "newsletter.placeholder", label: "Email placeholder" },
      { kind: "text", path: "newsletter.subscribe", label: "Subscribe button" },
      { kind: "text", path: "newsletter.sending", label: "Sending state" },
      { kind: "text", path: "newsletter.subscribed", label: "Subscribed state" },
      { kind: "text", path: "newsletter.error", label: "Error message" },
    ],
  },
  {
    key: "site_manifest",
    title: "PWA Manifest",
    description: "Browser install / home-screen manifest texts.",
    fields: [
      { kind: "text", path: "name", label: "App name" },
      { kind: "text", path: "short_name", label: "Short name" },
      { kind: "textarea", path: "description", label: "Description", rows: 3 },
    ],
  },
];
